using Cleansia.Core.AppServices.Abstractions;
using Cleansia.Core.AppServices.Authentication;
using Cleansia.Core.AppServices.Common;
using Cleansia.Core.AppServices.Features.Auth.Validators;
using Cleansia.Core.AppServices.Services.Interfaces;
using Cleansia.Core.AppServices.Shared.DTOs.ResponseModels;
using Cleansia.Core.Domain.Enums;
using Cleansia.Core.Domain.Repositories;
using Cleansia.Core.Domain.Users;
using Cleansia.Infra.Common.Validations;
using FluentValidation;
using Microsoft.Extensions.Logging;

namespace Cleansia.Core.AppServices.Features.Auth;

public class AppleAuth
{
    public class Validator : BaseAuthValidator<Command>
    {
        public Validator()
        {
            // Identity (email, subject, email_verified) and the account-type safety guard are bound from
            // the VERIFIED Apple identity token in the Handler, never from the client (S1). The validator
            // therefore keeps ONLY shape rules on the fields the handler actually uses: the token and the
            // raw nonce (both verified server-side). The display name is optional here — Apple returns a
            // name ONLY on the first authorization, may omit the family name, and sends no name at all on
            // every later sign-in, so requiring it would reject legitimate logins. When a value is present
            // it is only length-capped; identity never depends on it.
            RuleFor(command => command.FirstName)
                .MaximumLength(50)
                .WithMessage(BusinessErrorMessage.MaxLength)
                .WithErrorCode(nameof(Command.FirstName));

            RuleFor(command => command.LastName)
                .MaximumLength(50)
                .WithMessage(BusinessErrorMessage.MaxLength)
                .WithErrorCode(nameof(Command.LastName));

            RuleFor(command => command.IdentityToken)
                .NotEmpty()
                .WithMessage(BusinessErrorMessage.Required)
                .WithErrorCode(nameof(Command.IdentityToken));

            RuleFor(command => command.RawNonce)
                .NotEmpty()
                .WithMessage(BusinessErrorMessage.Required)
                .WithErrorCode(nameof(Command.RawNonce));
        }
    }

    public record Command(
        string IdentityToken,
        string RawNonce,
        string? FirstName,
        string? LastName)
        : ICommand<JwtTokenResponse>;

    public class Handler(
        IAppleTokenVerifier appleTokenVerifier,
        ITokenService tokenService,
        ICartRepository cartRepository,
        IUserRepository userRepository,
        IHostAudienceProvider hostAudience,
        ILogger<Handler> logger)
        : ICommandHandler<Command, JwtTokenResponse>
    {
        private const string AppleRelayEmailDomain = "privaterelay.appleid.com";

        // These two, and DeriveNameFromEmail as a whole, are not just defaults: their output is the ONLY
        // evidence User.ReplaceSystemGeneratedName has that a stored name was generated by us rather than
        // typed by the user. Changing either value orphans every row already written with the old one —
        // those names then read as user-authored forever and Apple's one real-name payload can no longer
        // displace them. Do not change casually; a change needs a data fix-up alongside it.
        private const string FallbackFirstName = "Cleansia";
        private const string FallbackLastName = "Customer";
        private const int MinDerivedNameLength = 2;
        private const int MaxNameLength = 50;
        private static readonly char[] EmailNameSeparators = ['.', '_', '-', '+'];

        public async Task<BusinessResult<JwtTokenResponse>> Handle(Command command, CancellationToken cancellationToken)
        {
            // S1 server-truth-identity: verify the Apple identity token server-side (RS256/JWKS, aud/iss/
            // lifetime, and the SHA256(rawNonce)==nonce binding) and bind identity from the VERIFIED claims
            // (email + subject + email_verified), never the client-supplied request fields.
            var claims = await appleTokenVerifier.VerifyAsync(command.IdentityToken, command.RawNonce, cancellationToken);
            if (claims is null)
            {
                return BusinessResult.Failure<JwtTokenResponse>(
                    new Error(nameof(Command.IdentityToken), BusinessErrorMessage.InvalidAppleUserToken));
            }

            // Resolve by the Apple sub FIRST: it is server-verified from the token (never client-supplied),
            // immutable for this Apple ID within our developer team, and the ONLY identity Apple sends on a
            // returning sign-in — it omits the email after the user's first authorization, so an
            // email-only lookup locked returning users out. The email is a fallback for accounts
            // provisioned before their sub was ever seen — and only when APPLE vouched for it (S1):
            // matching by email also BINDS this token's sub to that row below, permanently, so an
            // unverified address must reach neither the account nor its identity anchor. A sub match
            // carries its own proof and is deliberately not gated — that sub was bound while the email
            // was verified, and re-gating it would lock out every returning user (Apple stops sending the
            // email, and with it a meaningful email_verified, after the first authorization).
            var user = await userRepository.GetByAppleIdIgnoringTenantAsync(claims.Subject, cancellationToken);
            if (user is null && claims.EmailVerified && !string.IsNullOrWhiteSpace(claims.Email))
            {
                user = await userRepository.GetByEmailIgnoringTenantAsync(claims.Email, cancellationToken);
            }

            if (user is not null)
            {
                // S1: the account-type guard MUST run against the account the handler actually
                // authenticates — resolved from the VERIFIED claims — not a client-supplied field. Block an
                // Apple login from binding into an existing password (Internal) OR Google account that
                // shares this verified email (the verified-email-collision takeover Google's hardening
                // closed). A sub-matched account keeps its stored email untouched: rewriting it would
                // collide with the (TenantId, Email) unique index and silently merge two accounts.
                // The rejection names the provider the colliding account ACTUALLY uses (the same switch
                // the password login uses) — telling a Google user to "sign in with your email and
                // password" sends them to a dead end. No extra disclosure: the caller already holds a
                // token Apple minted for this verified identity.
                if (user.AuthenticationType != AuthenticationType.Apple)
                {
                    return BusinessResult.Failure<JwtTokenResponse>(
                        new Error(nameof(Command.IdentityToken), AuthTypeErrorMessages.For(user.AuthenticationType)));
                }

                if (!user.IsActive)
                {
                    return BusinessResult.Failure<JwtTokenResponse>(
                        new Error(nameof(Command.IdentityToken), BusinessErrorMessage.InvalidPassword));
                }

                // Heal an account stored with a blank name. Apple sends the name ONLY on the first
                // authorization, so accounts provisioned while this flow was broken are blank and a normal
                // later sign-in carries nothing to fill them with — which leaves the customer unable to
                // book (an empty name fails the profile-complete gate and CreateOrder's CustomerName rule)
                // with no way out. So fall back to the SAME verified-email derivation used at provisioning
                // when the client sends nothing, making every later sign-in self-healing rather than
                // depending on the user revoking the app in Settings.
                // Passing the derivation alongside the supplied name is what lets the domain tell a name we
                // generated from one the user typed: ReplaceSystemGeneratedName promotes the genuine Apple
                // payload over the former (it arrives exactly once — revoke + re-authorize — and must not
                // be dropped on the floor) and never touches the latter.
                // Bind the verified sub if this row was matched by the EMAIL fallback (an account
                // provisioned before subs were stored). Apple only sends the email on the first
                // authorization, so without this the next sign-in has neither a matching sub nor an email
                // to fall back to and the user is locked out of their own account. No-ops when a sub is
                // already bound — an existing sub is never rewritten (S1).
                user.LinkAppleId(claims.Subject);

                var (suppliedFirstName, suppliedLastName) = SplitSuppliedName(command.FirstName, command.LastName);
                var (derivedFirstName, derivedLastName) = DeriveNameFromEmail(user.Email);
                user.ReplaceSystemGeneratedName(suppliedFirstName, suppliedLastName, derivedFirstName, derivedLastName);

                return BusinessResult.Success(await tokenService.GenerateTokenAsync(user, rememberMe: true, hostAudience.Audience, cancellationToken));
            }

            // Provision only when Apple reports a verified email — reject an unverifiable one rather than
            // create an account around it. No email at all means Apple has authorized this app for that
            // Apple ID before, yet no account carries the sub: nothing safe to provision, so fail closed.
            if (!claims.EmailVerified || string.IsNullOrWhiteSpace(claims.Email))
            {
                logger.LogWarning(
                    "Apple sign-in rejected: no account matched the verified subject and a new one cannot be " +
                    "provisioned (hasEmailClaim: {HasEmailClaim}, emailVerified: {EmailVerified}).",
                    claims.Email is not null,
                    claims.EmailVerified);

                return BusinessResult.Failure<JwtTokenResponse>(
                    new Error(nameof(Command.IdentityToken), BusinessErrorMessage.InvalidAppleUserToken));
            }

            // The display name comes from the command when Apple sent one — it only ever does on the FIRST
            // authorization, and may arrive partial — and otherwise from the verified email
            // (see ResolveDisplayName). Identity itself is always the verified claims.
            var (firstName, lastName) = ResolveDisplayName(command.FirstName, command.LastName, claims.Email);
            var userEntity = User.CreateWithApple(claims.Email, firstName, lastName, claims.Subject);

            userRepository.Add(userEntity);
            cartRepository.Add(Cart.CreateWithUser(userEntity));

            return BusinessResult.Success(await tokenService.GenerateTokenAsync(userEntity, rememberMe: true, hostAudience.Audience, cancellationToken));
        }

        // A provisioned account must NEVER carry a blank name part: UpdateCurrentUser validates both
        // NotEmpty and CreateOrder requires a CustomerName of at least 2 characters, so an empty name
        // locks the customer out of booking on an account Apple can never re-send a name for. Anything the
        // client supplied wins; each blank part falls back to the VERIFIED email's local part
        // ("jane.doe@x.com" -> Jane Doe) and then to a neutral placeholder the user can edit.
        private static (string FirstName, string LastName) ResolveDisplayName(string? firstName, string? lastName, string verifiedEmail)
        {
            var (first, last) = SplitSuppliedName(firstName, lastName);
            if (first.Length > 0 && last.Length > 0)
            {
                return (first, last);
            }

            var (derivedFirst, derivedLast) = DeriveNameFromEmail(verifiedEmail);

            return (
                first.Length > 0 ? first : derivedFirst,
                last.Length > 0 ? last : derivedLast);
        }

        // Apple hands the name only on the first authorization and may omit either part entirely, or fold
        // the whole name into a single field: when only ONE space-separated field arrives, split it so the
        // other part isn't needlessly left blank (and doesn't get back-filled with a placeholder that then
        // reads as user-authored forever). Symmetric on purpose — the sole field can be either one,
        // depending on which the user cleared in Apple's consent sheet — and the split is by FIRST space
        // when the given name is the populated one, by LAST space when the family name is, so multi-word
        // surnames ("Anna van der Berg") stay whole. A first/last swap is possible either way and is
        // accepted: the user can correct it in Edit profile, whereas a placeholder is much harder to
        // displace later.
        private static (string FirstName, string LastName) SplitSuppliedName(string? firstName, string? lastName)
        {
            var first = (firstName ?? string.Empty).Trim();
            var last = (lastName ?? string.Empty).Trim();

            if (last.Length == 0 && first.Contains(' '))
            {
                var separatorIndex = first.IndexOf(' ');
                last = first[(separatorIndex + 1)..].Trim();
                first = first[..separatorIndex];
            }
            else if (first.Length == 0 && last.Contains(' '))
            {
                var separatorIndex = last.LastIndexOf(' ');
                first = last[..separatorIndex].Trim();
                last = last[(separatorIndex + 1)..];
            }

            return (first, last);
        }

        private static (string FirstName, string LastName) DeriveNameFromEmail(string verifiedEmail)
        {
            // An Apple private-relay local part is a random token, never name-shaped, so deriving from it
            // would persist gibberish as the user's name — go straight to the placeholder instead.
            var isRelayAddress = verifiedEmail.EndsWith(AppleRelayEmailDomain, StringComparison.OrdinalIgnoreCase);
            var localPart = verifiedEmail.Split('@')[0];
            string[] parts = isRelayAddress
                ? []
                : localPart
                    .Split(EmailNameSeparators, StringSplitOptions.RemoveEmptyEntries)
                    .Select(ToNamePart)
                    .Where(part => part.Length >= MinDerivedNameLength)
                    .ToArray();

            return (
                parts.Length > 0 ? parts[0] : FallbackFirstName,
                parts.Length > 1 ? parts[1] : FallbackLastName);
        }

        // Digits and punctuation are dropped ("jane.doe2024" -> Jane, Doe) and the result capitalised;
        // a leftover shorter than MinDerivedNameLength is discarded by the caller as not name-shaped.
        private static string ToNamePart(string token)
        {
            var letters = new string(token.Where(char.IsLetter).Take(MaxNameLength).ToArray());

            return letters.Length == 0
                ? string.Empty
                : char.ToUpperInvariant(letters[0]) + letters[1..].ToLowerInvariant();
        }
    }
}
