export enum CleansiaPartnerRoute {
  HOME = '',
  DASHBOARD = 'dashboard',
  PROFILE = 'profile',
  ORDERS = 'orders',
  DISPUTES = 'disputes',
  INVOICES = 'invoices',
  MY_PAY = 'my-pay',
  LOGIN = 'login',
  REGISTER = 'register',
  FORGOT_PASSWORD = 'forgot-password',
  CONFIRM_EMAIL = 'confirm-email',
  GDPR = 'gdpr',
}

export enum CleansiaAdminRoute {
  HOME = '',
  LOGIN = 'login',
  UNAUTHORIZED = 'unauthorized',
  EMPLOYEE_MANAGEMENT = 'employee-management',
  PAY_PERIODS = 'pay-periods',
  ORDER_MANAGEMENT = 'order-management',
  DISPUTE_MANAGEMENT = 'dispute-management',
  INVOICE_MANAGEMENT = 'invoice-management',
  REPORTS = 'reports',
  SERVICE_MANAGEMENT = 'service-management',
  PACKAGE_MANAGEMENT = 'package-management',
  ADMIN_USER_MANAGEMENT = 'admin-user-management',
  LANGUAGE_MANAGEMENT = 'language-management',
  COUNTRY_MANAGEMENT = 'country-management',
  SERVICE_AREA_MANAGEMENT = 'service-area-management',
  CURRENCY_MANAGEMENT = 'currency-management',
  COMPANY_INFO = 'company-info',
  TEMPLATE_MANAGEMENT = 'template-management',
  PAY_CONFIG_MANAGEMENT = 'pay-config-management',
  MEMBERSHIP_PLAN_MANAGEMENT = 'membership-plan-management',
  DATA_PROTECTION = 'data-protection',
  AUDIT_LOG = 'audit-log',
  PROFILE = 'profile',
}

export enum CleansiaCustomerRoute {
  HOME = '',
  LOGIN = 'login',
  REGISTER = 'register',
  // Public referral landing — /r/{code}. Single source for both the share
  // URL (rewards) and the app route so they cannot drift.
  REFERRAL_LANDING = 'r',
  CONFIRM_EMAIL = 'confirm-email',
  FORGOT_PASSWORD = 'forgot-password',
  SERVICES = 'services',
  ORDER = 'order',
  ORDERS = 'orders',
  PROFILE = 'profile',
  SAVED_ADDRESSES = 'saved-addresses',
  DISPUTES = 'disputes',
  REWARDS = 'rewards',
  MEMBERSHIP = 'membership',
  GDPR = 'gdpr',
  CHECKOUT_SUCCESS = 'checkout/success',
  CHECKOUT_CANCEL = 'checkout/cancel',
  TRACK_ORDER = 'track-order',
  NOT_FOUND = 'not-found',
}

export enum CommonRoute {
  HOME = '',
  NOT_FOUND = 'not-found',
  LOGIN = 'login',
  LOGOUT = 'logout',
}
