package cz.cleansia.partner.features.profile

import cz.cleansia.partner.api.model.DocumentType
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Pins the list of document types the upload picker offers.
 *
 * The picker used to carry its own hardcoded English labels, which drifted
 * from the translated labels the document rows show in the very same dialog.
 * It now derives every option from `documentTypeLabel`, so the labels cannot
 * drift again — but the *set* of options still lives in a hand-written list,
 * because `DocumentType.entries` would silently admit a type that has no
 * label branch.
 *
 * That hand-written list is what this test guards. `DocumentType` is
 * OpenAPI-generated and is regenerated by the owner whenever the backend enum
 * changes; adding a member makes `documentTypeLabel`'s `when` fail to compile,
 * which is the loud half of the signal. This is the quiet half: a member that
 * exists, compiles, has a label, and is simply never offered for upload.
 */
class DocumentTypeOptionsTest {

    @Test
    fun `every document type the API defines can be picked`() {
        assertEquals(DocumentType.entries.toList(), documentTypeOptions)
    }

    @Test
    fun `no type is offered twice`() {
        assertEquals(documentTypeOptions.size, documentTypeOptions.distinct().size)
    }

    @Test
    fun `options are ordered by the value sent to the server`() {
        // The picker keys its selection round-trip off value.toString(); the
        // order is also what the cleaner reads top-to-bottom, so it should be
        // the API's own order rather than whatever the list was typed in.
        assertEquals(
            documentTypeOptions.map { it.value }.sorted(),
            documentTypeOptions.map { it.value },
        )
    }
}
