-- Backfill full 5-language (en/cs/sk/uk/ru) Translations for every seeded Service and Package.
--
-- Why: the mobile + web apps render service/package names via translations[lang].Name with an English
-- fallback. The seed historically carried only en/cs/ru (and some live DEV rows were created with empty
-- Translations), so Slovak/Ukrainian users — and any row missing its language — saw the English fallback.
-- This backfills sk + uk (and re-asserts en/cs/ru) so all five languages resolve.
--
-- Idempotent: matches rows by their English "Name" and overwrites "Translations" with the full map, so it
-- is safe to re-run. Apply to the DEV database (the seed below is also updated for fresh installs).
-- Slovak derived from the Czech copy, Ukrainian from the Russian copy.

BEGIN;

-- ===== Services =====
UPDATE public."Services" SET "Translations" = '{"en":{"Name":"General Cleaning","Description":"Standard cleaning of all rooms including dusting, vacuuming, and sanitizing"},"cs":{"Name":"Obecný úklid","Description":"Standardní úklid všech místností včetně otírání prachu, vysávání a dezinfekce"},"sk":{"Name":"Všeobecné upratovanie","Description":"Štandardné upratovanie všetkých miestností vrátane utierania prachu, vysávania a dezinfekcie"},"uk":{"Name":"Загальне прибирання","Description":"Стандартне прибирання всіх кімнат, включно з витиранням пилу, пилососом та дезінфекцією"},"ru":{"Name":"Общая уборка","Description":"Стандартная уборка всех комнат включая протирание пыли, пылесос и дезинфекцию"}}' WHERE "Name" = 'General Cleaning';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Deep Cleaning","Description":"Thorough cleaning including baseboards, inside appliances, and detailed sanitization"},"cs":{"Name":"Hloubkový úklid","Description":"Důkladný úklid včetně lišt, vnitřků spotřebičů a detailní dezinfekce"},"sk":{"Name":"Hĺbkové upratovanie","Description":"Dôkladné upratovanie vrátane líšt, vnútra spotrebičov a detailnej dezinfekcie"},"uk":{"Name":"Глибоке прибирання","Description":"Ретельне прибирання, включно з плінтусами, всередині побутової техніки та детальною дезінфекцією"},"ru":{"Name":"Глубокая уборка","Description":"Тщательная уборка включая плинтуса, внутри бытовой техники и детальная дезинфекция"}}' WHERE "Name" = 'Deep Cleaning';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Bathroom Cleaning","Description":"Specialized bathroom cleaning with tile scrubbing and grout cleaning"},"cs":{"Name":"Úklid koupelny","Description":"Specializovaný úklid koupelny s drhnáním dlaždic a čištěním spár"},"sk":{"Name":"Upratovanie kúpeľne","Description":"Špecializované upratovanie kúpeľne s drhnutím dlaždíc a čistením škár"},"uk":{"Name":"Прибирання ванної","Description":"Спеціалізоване прибирання ванної з чищенням плитки та швів"},"ru":{"Name":"Уборка ванной","Description":"Специализированная уборка ванной с чисткой плитки и швов"}}' WHERE "Name" = 'Bathroom Cleaning';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Kitchen Deep Clean","Description":"Comprehensive kitchen cleaning including oven, refrigerator, and cabinets"},"cs":{"Name":"Hloubkový úklid kuchyně","Description":"Komplexní úklid kuchyně včetně trouby, lednice a skříněk"},"sk":{"Name":"Hĺbkové upratovanie kuchyne","Description":"Komplexné upratovanie kuchyne vrátane rúry, chladničky a skriniek"},"uk":{"Name":"Глибоке прибирання кухні","Description":"Комплексне прибирання кухні, включно з духовкою, холодильником та шафами"},"ru":{"Name":"Глубокая уборка кухни","Description":"Комплексная уборка кухни включая духовку, холодильник и шкафы"}}' WHERE "Name" = 'Kitchen Deep Clean';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Window Cleaning","Description":"Interior and exterior window cleaning with streak-free finish"},"cs":{"Name":"Mytí oken","Description":"Mytí oken zevnitř i zvenčí bez šmouh"},"sk":{"Name":"Umývanie okien","Description":"Umývanie okien zvnútra aj zvonku bez šmúh"},"uk":{"Name":"Миття вікон","Description":"Миття вікон зсередини та зовні без розводів"},"ru":{"Name":"Мытье окон","Description":"Мытье окон изнутри и снаружи без разводов"}}' WHERE "Name" = 'Window Cleaning';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Carpet Cleaning","Description":"Professional carpet steam cleaning and stain removal"},"cs":{"Name":"Čištění koberců","Description":"Profesionální parní čištění koberců a odstraňování skvrn"},"sk":{"Name":"Čistenie kobercov","Description":"Profesionálne parné čistenie kobercov a odstraňovanie škvŕn"},"uk":{"Name":"Чищення килимів","Description":"Професійне парове чищення килимів та видалення плям"},"ru":{"Name":"Чистка ковров","Description":"Профессиональная паровая чистка ковров и удаление пятен"}}' WHERE "Name" = 'Carpet Cleaning';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Upholstery Cleaning","Description":"Deep cleaning of sofas, chairs, and fabric furniture"},"cs":{"Name":"Čištění čalounění","Description":"Hloubkové čištění sedaček, židlí a látkového nábytku"},"sk":{"Name":"Čistenie čalúnenia","Description":"Hĺbkové čistenie sedačiek, stoličiek a látkového nábytku"},"uk":{"Name":"Чищення оббивки","Description":"Глибоке чищення диванів, крісел та тканинних меблів"},"ru":{"Name":"Чистка обивки","Description":"Глубокая чистка диванов, кресел и тканевой мебели"}}' WHERE "Name" = 'Upholstery Cleaning';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Post-Construction Cleanup","Description":"Specialized cleaning after renovation or construction work"},"cs":{"Name":"Úklid po rekonstrukci","Description":"Specializovaný úklid po rekonstrukci nebo stavebních pracích"},"sk":{"Name":"Upratovanie po rekonštrukcii","Description":"Špecializované upratovanie po rekonštrukcii alebo stavebných prácach"},"uk":{"Name":"Прибирання після ремонту","Description":"Спеціалізоване прибирання після ремонту або будівельних робіт"},"ru":{"Name":"Уборка после ремонта","Description":"Специализированная уборка после ремонта или строительных работ"}}' WHERE "Name" = 'Post-Construction Cleanup';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Move-in/Move-out Cleaning","Description":"Complete cleaning for moving in or out of property"},"cs":{"Name":"Úklid při stěhování","Description":"Kompletní úklid při nastěhování nebo vystěhování z nemovitosti"},"sk":{"Name":"Upratovanie pri sťahovaní","Description":"Kompletné upratovanie pri nasťahovaní alebo vysťahovaní z nehnuteľnosti"},"uk":{"Name":"Прибирання при переїзді","Description":"Повне прибирання при в''їзді або виїзді з нерухомості"},"ru":{"Name":"Уборка при переезде","Description":"Полная уборка при въезде или выезде из недвижимости"}}' WHERE "Name" = 'Move-in/Move-out Cleaning';

UPDATE public."Services" SET "Translations" = '{"en":{"Name":"Eco-Friendly Cleaning","Description":"Green cleaning using only eco-friendly and non-toxic products"},"cs":{"Name":"Ekologický úklid","Description":"Zelený úklid používající pouze ekologické a netoxické produkty"},"sk":{"Name":"Ekologické upratovanie","Description":"Zelené upratovanie používajúce iba ekologické a netoxické produkty"},"uk":{"Name":"Екологічне прибирання","Description":"Зелене прибирання з використанням лише екологічних та нетоксичних продуктів"},"ru":{"Name":"Экологическая уборка","Description":"Зеленая уборка с использованием только экологически чистых и нетоксичных продуктов"}}' WHERE "Name" = 'Eco-Friendly Cleaning';

-- ===== Packages =====
UPDATE public."Packages" SET "Translations" = '{"en":{"Name":"Essential Clean","Description":"Perfect for regular maintenance cleaning of your home"},"cs":{"Name":"Základní úklid","Description":"Ideální pro pravidelný udržovací úklid vašeho domova"},"sk":{"Name":"Základné upratovanie","Description":"Ideálne pre pravidelné udržiavacie upratovanie vášho domova"},"uk":{"Name":"Основне прибирання","Description":"Ідеально для регулярного підтримуючого прибирання вашого дому"},"ru":{"Name":"Основная уборка","Description":"Идеально для регулярной поддерживающей уборки вашего дома"}}' WHERE "Name" = 'Essential Clean';

UPDATE public."Packages" SET "Translations" = '{"en":{"Name":"Complete Home Clean","Description":"Comprehensive cleaning package for the entire home"},"cs":{"Name":"Kompletní úklid domova","Description":"Komplexní úklidový balíček pro celý domov"},"sk":{"Name":"Kompletné upratovanie domova","Description":"Komplexný upratovací balík pre celý domov"},"uk":{"Name":"Повне прибирання дому","Description":"Комплексний пакет прибирання для всього дому"},"ru":{"Name":"Полная уборка дома","Description":"Комплексный пакет уборки для всего дома"}}' WHERE "Name" = 'Complete Home Clean';

UPDATE public."Packages" SET "Translations" = '{"en":{"Name":"Deep Clean Premium","Description":"Intensive deep cleaning for thoroughly clean spaces"},"cs":{"Name":"Prémiový hloubkový úklid","Description":"Intenzivní hloubkový úklid pro dokonale čisté prostory"},"sk":{"Name":"Prémiové hĺbkové upratovanie","Description":"Intenzívne hĺbkové upratovanie pre dokonale čisté priestory"},"uk":{"Name":"Преміум глибоке прибирання","Description":"Інтенсивне глибоке прибирання для ідеально чистих приміщень"},"ru":{"Name":"Премиум глубокая уборка","Description":"Интенсивная глубокая уборка для идеально чистых помещений"}}' WHERE "Name" = 'Deep Clean Premium';

UPDATE public."Packages" SET "Translations" = '{"en":{"Name":"Kitchen & Bathroom Focus","Description":"Specialized package focusing on kitchen and bathroom deep cleaning"},"cs":{"Name":"Zaměření na kuchyň a koupelnu","Description":"Specializovaný balíček zaměřený na hloubkový úklid kuchyně a koupelny"},"sk":{"Name":"Zameranie na kuchyňu a kúpeľňu","Description":"Špecializovaný balík zameraný na hĺbkové upratovanie kuchyne a kúpeľne"},"uk":{"Name":"Фокус на кухню та ванну","Description":"Спеціалізований пакет з акцентом на глибоке прибирання кухні та ванної"},"ru":{"Name":"Фокус на кухню и ванную","Description":"Специализированный пакет с акцентом на глубокую уборку кухни и ванной"}}' WHERE "Name" = 'Kitchen & Bathroom Focus';

UPDATE public."Packages" SET "Translations" = '{"en":{"Name":"Eco-Green Package","Description":"Complete eco-friendly cleaning using only green products"},"cs":{"Name":"Eko-zelený balíček","Description":"Kompletní ekologický úklid používající pouze zelené produkty"},"sk":{"Name":"Eko-zelený balík","Description":"Kompletné ekologické upratovanie používajúce iba zelené produkty"},"uk":{"Name":"Еко-зелений пакет","Description":"Повне екологічне прибирання з використанням лише зелених продуктів"},"ru":{"Name":"Эко-зеленый пакет","Description":"Полная экологическая уборка с использованием только зеленых продуктов"}}' WHERE "Name" = 'Eco-Green Package';

UPDATE public."Packages" SET "Translations" = '{"en":{"Name":"Moving Day Special","Description":"Perfect for move-in or move-out situations"},"cs":{"Name":"Speciál pro den stěhování","Description":"Ideální pro situace nastěhování nebo vystěhování"},"sk":{"Name":"Špeciál pre deň sťahovania","Description":"Ideálne pre situácie nasťahovania alebo vysťahovania"},"uk":{"Name":"Спеціальний пакет для переїзду","Description":"Ідеально для ситуацій в''їзду або виїзду"},"ru":{"Name":"Специальный пакет для переезда","Description":"Идеально для ситуаций въезда или выезда"}}' WHERE "Name" = 'Moving Day Special';

UPDATE public."Packages" SET "Translations" = '{"en":{"Name":"Post-Renovation Clean","Description":"Specialized cleaning after construction or renovation work"},"cs":{"Name":"Úklid po rekonstrukci","Description":"Specializovaný úklid po stavebních nebo rekonstrukčních pracích"},"sk":{"Name":"Upratovanie po rekonštrukcii","Description":"Špecializované upratovanie po stavebných alebo rekonštrukčných prácach"},"uk":{"Name":"Прибирання після ремонту","Description":"Спеціалізоване прибирання після будівельних або ремонтних робіт"},"ru":{"Name":"Уборка после ремонта","Description":"Специализированная уборка после строительных или ремонтных работ"}}' WHERE "Name" = 'Post-Renovation Clean';

UPDATE public."Packages" SET "Translations" = '{"en":{"Name":"Luxury Full Service","Description":"Premium package with all services included"},"cs":{"Name":"Luxusní kompletní služba","Description":"Prémiový balíček se všemi zahrnutými službami"},"sk":{"Name":"Luxusná kompletná služba","Description":"Prémiový balík so všetkými zahrnutými službami"},"uk":{"Name":"Розкішний повний сервіс","Description":"Преміум пакет з усіма включеними послугами"},"ru":{"Name":"Роскошный полный сервис","Description":"Премиум пакет со всеми включенными услугами"}}' WHERE "Name" = 'Luxury Full Service';

COMMIT;
