name: Backend CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x.x

      - name: List files in Core.Domain
        run: ls -R ./src/Cleansia.Core.Domain

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./src
      - name: Run tests
        run: dotnet test --configuration Release --no-build
        working-directory: ./src