name: Frontend CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./src/Cleansia.App/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./src/Cleansia.App

      - name: Build Partner App
        run: npm run build:cleansia-partner
        working-directory: ./src/Cleansia.App

      - name: Build Admin App
        run: npm run build:cleansia-admin
        working-directory: ./src/Cleansia.App
